Feat(Back OpeningHour): adding entity opening hour
ESGI-69/challenge-5A-S1 pull request #116
Opened 2023-11-08 13:49 UTC by sguenier

2023-11-09 09:15 UTC, sguenier commented
![image](https://github.com/ESGI-69/challenge-5A-S1/assets/93766446/abe78b2c-a810-4678-9391-5a65b4434738)

2023-11-09 09:16 UTC, mrpinkcat requested changes

2023-11-09 09:16 UTC, mrpinkcat commented on frontend/src/components/OpeningHours/OpeningHours.module.scss
> +    border-radius: 5px;
```suggestion
    border-radius: var(--radius-2);
```

2023-11-09 09:16 UTC, mrpinkcat commented on frontend/src/components/OpeningHours/OpeningHours.module.scss
> +    border: solid 1px var(--gray-4);
```suggestion
    border: var(--border-size-1) solid var(--gray-4);
```

2023-11-09 09:16 UTC, mrpinkcat commented on frontend/src/components/OpeningHours/OpeningHours.module.scss
> +    padding: 2vh 3vw;
Pas de `vh`/`vw`

2023-11-09 09:16 UTC, mrpinkcat commented on frontend/src/components/OpeningHours/OpeningHours.module.scss
> +    padding: 1vh 0;
Pas de `vh`/`vw`

2023-11-09 09:16 UTC, mrpinkcat commented on frontend/src/components/OpeningHours/index.jsx
> +    6: t('saturday'),
Ça tu peux le mettre dans le `base.json` comme ça va etre commun a toute l'app

```suggestion
    0: t('weekDays.sunday', { ns: 'base' }),
    1: t('weekDays.monday', { ns: 'base' }),
    2: t('weekDays.tuesday', { ns: 'base' }),
    3: t('weekDays.wenesday', { ns: 'base' }),
    4: t('weekDays.thursday', { ns: 'base' }),
    5: t('weekDays.friday', { ns: 'base' }),
    6: t('weekDays.saturday', { ns: 'base' }),
```

Et ton `base.json` resemblera a ça
```json
{
  "weekDays": {
    "monday": "Lundi"
  }
}
```

2023-11-09 09:16 UTC, mrpinkcat commented on frontend/src/pages/Library.jsx
> +        ])}
préfère passé ça en prop, pas dans le children, ça t'évitera de faire un JSON stringify. Tu pourras passer directement un object

2023-11-09 10:02 UTC, mrpinkcat approved these changes

2023-11-09 10:05 UTC, Timdev0 approved these changes

2023-11-12 02:12 UTC, SebGrd approved these changes

2023-11-12 02:12 UTC, merged