feat:popin +gallery, add popin to view images from gallery
ESGI-69/challenge-5A-S1 pull request #134
Opened 2023-11-11 23:21 UTC by ycenta

ajout du component popin pour la gallery 

resultat en video : 

https://streamable.com/drmzhj

2023-11-12 16:30 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/index.jsx
> +            {index === 4 && pictures.length > 5 ? <Button href="javascript:void" onClick={openGallery} className={styles.GalleryMoreBtn}>{t('viewPhotos', { count: pictures.length })}</Button> : null}
```suggestion
            {index === 4 && pictures.length > 5 ? <Button variant="secondary" onClick={openGallery} className={styles.GalleryMoreBtn}>{t('viewPhotos', { count: pictures.length })}</Button> : null}
```

Utilise le type secondary il n'y a pas de background

2023-11-12 16:38 UTC, mrpinkcat requested changes

2023-11-12 16:38 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/index.jsx
>  import Button from '../Button';
```suggestion
import Button from '@/components/lib/Button';
```

Utilise le `@` pour les chemins

2023-11-12 16:38 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/index.jsx
Enlève la gallery du dossier `lib`

2023-11-12 16:38 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/index.jsx
> +import Popin from '../../Popin';
```suggestion
import Popin from '@/components/Popin';
```

2023-11-15 14:33 UTC, mrpinkcat submitted a review, later dismissed

2023-11-16 08:25 UTC, SebGrd requested changes
<img width="104" alt="image" src="https://github.com/ESGI-69/challenge-5A-S1/assets/43199628/fd21e618-1ce6-48ce-b674-d62a0267a743">
<img width="150" alt="image" src="https://github.com/ESGI-69/challenge-5A-S1/assets/43199628/7df05b17-a529-47ef-b709-8000a5aed945">
Voici visuellement des trucs que j'ai relevé

2023-11-16 08:25 UTC, SebGrd commented on frontend/src/components/Gallery/index.jsx
> +            <Button className={styles.GallerySlideshowArrow} onClick={() => setPictureIndex((pictureIndex + 1) % pictures.length)}>→</Button>
Ajoute un variant sur le bouton + une vrai icone de flèche

2023-11-16 18:45 UTC, mrpinkcat commented on frontend/src/components/Gallery/index.jsx
> +            <Button className={styles.GallerySlideshowArrow} onClick={() => setPictureIndex((pictureIndex + 1) % pictures.length)}>→</Button>
tout pareil

2023-11-16 20:00 UTC, SebGrd commented on frontend/src/components/Gallery/index.jsx
> +            <Button className={styles.GallerySlideshowArrow} onClick={() => setPictureIndex((pictureIndex + 1) % pictures.length)}>→</Button>
```svg
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M15.6059 7.04961L8.94475 0.380176C8.81805 0.258738 8.66865 0.163545 8.50511 0.10006C8.18077 -0.0333532 7.81696 -0.0333532 7.49261 0.10006C7.32908 0.163545 7.17968 0.258738 7.05298 0.380176L0.391799 7.04961C0.267584 7.17398 0.169051 7.32163 0.101826 7.48413C0.0346007 7.64663 0 7.82079 0 7.99668C0 8.35189 0.140935 8.69256 0.391799 8.94374C0.642664 9.19491 0.98291 9.33602 1.33769 9.33602C1.69246 9.33602 2.03271 9.19491 2.28357 8.94374L6.66663 4.54191V14.6661C6.66663 15.0199 6.80699 15.3592 7.05683 15.6093C7.30667 15.8595 7.64553 16 7.99886 16C8.35219 16 8.69105 15.8595 8.9409 15.6093C9.19074 15.3592 9.3311 15.0199 9.3311 14.6661V4.54191L13.7142 8.94374C13.838 9.06876 13.9853 9.16799 14.1477 9.23571C14.31 9.30343 14.4842 9.3383 14.66 9.3383C14.8359 9.3383 15.01 9.30343 15.1724 9.23571C15.3347 9.16799 15.4821 9.06876 15.6059 8.94374C15.7308 8.81973 15.8299 8.6722 15.8975 8.50966C15.9652 8.34711 16 8.17276 16 7.99668C16 7.82059 15.9652 7.64624 15.8975 7.48369C15.8299 7.32115 15.7308 7.17362 15.6059 7.04961Z" fill="#272727"/>
</svg>
```

2023-11-16 20:00 UTC, SebGrd commented on frontend/src/components/Gallery/index.jsx
> +            <Button className={styles.GallerySlideshowArrow} onClick={() => setPictureIndex((pictureIndex + 1) % pictures.length)}>→</Button>
(c'est la fleche)

2023-11-18 16:52 UTC, mrpinkcat approved these changes

2023-11-18 19:49 UTC, SebGrd approved these changes

2023-11-20 22:40 UTC, mrpinkcat approved these changes

2023-11-20 22:41 UTC, merged