Create establisment page
ESGI-69/challenge-5A-S1 pull request #135
Opened 2023-11-13 01:43 UTC by mrpinkcat

2023-11-18 19:48 UTC, SebGrd requested changes

2023-11-18 19:48 UTC, SebGrd commented on frontend/src/contexts/api/EstablishmentContext.jsx
Tu peux rajouter la get() request stp ?
c'est pour les admins

2023-11-18 19:48 UTC, SebGrd commented on frontend/src/pages/website/Login/Login.module.scss
> +  @media screen and (width <= 1024px) {
je suis chaud qu'on ai des variables pour les breakpoints

2023-11-18 20:22 UTC, mrpinkcat commented on frontend/src/pages/website/Login/Login.module.scss
> +  @media screen and (width <= 1024px) {
Ouais effectivement bonne idée ! Je fais ça demain aprem

2023-11-19 16:44 UTC, mrpinkcat commented on frontend/src/contexts/api/EstablishmentContext.jsx
?

2023-11-19 18:53 UTC, mrpinkcat commented on frontend/src/contexts/api/EstablishmentContext.jsx
pas dans le scope de l'issue

2023-11-21 08:42 UTC, SebGrd approved these changes

2023-11-21 08:43 UTC, merged