fix crash on GET users/me
ESGI-69/challenge-5A-S1 pull request #138
Opened 2023-11-13 16:41 UTC by Timdev0

2023-11-13 18:20 UTC, ycenta approved these changes

2023-11-13 18:42 UTC, mrpinkcat commented on backend/src/Controller/User/GetUserMeController.php
> +        throw new BadRequestException('Not authenticated');
Il faut que tu throw une 401 ici

2023-11-13 18:42 UTC, mrpinkcat requested changes
401

2023-11-15 14:33 UTC, mrpinkcat approved these changes

2023-11-15 14:33 UTC, merged