create comment modal and handle post
ESGI-69/challenge-5A-S1 pull request #186
Opened 2024-02-05 15:14 UTC by Timdev0

average notation and global notation for an other PR

https://github.com/ESGI-69/challenge-5A-S1/assets/32125474/a916b987-50ef-4825-8ec4-7648469e5703

2024-02-07 21:51 UTC, Timdev0 commented on frontend/src/components/ModalSendReview/index.jsx
> +    4: 'Bien',
gros con

2024-02-07 21:52 UTC, mrpinkcat requested changes

2024-02-07 21:52 UTC, mrpinkcat commented on frontend/src/components/AppointmentCard/index.jsx
> +          {appointment.service.duration} min
```suggestion
          {appointment.service.duration} {$('minutes', { ns: 'base' })}
```

2024-02-07 21:52 UTC, mrpinkcat commented on frontend/src/components/ModalSendReview/index.jsx
> +    5: 'Excellent',
trad

2024-02-08 13:52 UTC, mrpinkcat approved these changes

2024-02-08 13:52 UTC, merged