Feat(BackOffice Employee): adding employee list + creation of employee
ESGI-69/challenge-5A-S1 pull request #189
Opened 2024-02-06 00:12 UTC by sguenier

2024-02-06 00:24 UTC, mrpinkcat commented on frontend/src/contexts/api/EmployeeContext.jsx
> +      console.error(error);
Hésite pas a mettre des toasts sur les erreurs de get aussi ;)

2024-02-07 20:48 UTC, sguenier commented
https://github.com/ESGI-69/challenge-5A-S1/assets/93766446/e7a38fea-468e-4b24-a8ba-053af364aa69

2024-02-07 21:55 UTC, mrpinkcat requested changes

2024-02-07 21:55 UTC, mrpinkcat commented on frontend/src/pages/backoffice/Employees/index.jsx
>          <h1>Employés</h1>
👀

2024-02-08 00:14 UTC, mrpinkcat approved these changes

2024-02-08 00:14 UTC, merged