20 create input component
ESGI-69/challenge-5A-S1 pull request #31
Opened 2023-10-16 15:09 UTC by Timdev0

2023-10-16 15:46 UTC, mrpinkcat requested changes

2023-10-16 15:46 UTC, mrpinkcat commented on frontend/src/App.jsx
> +        <Input id='TEst' placeholder="Placeholder" onChange={handleInputChange} />
Tu peux juste appeler `setInputValue` ici nan ?

2023-10-16 22:39 UTC, mrpinkcat requested changes
Met une prop pour le disable aussi 🥺

2023-10-17 08:40 UTC, SebGrd requested changes

2023-10-17 08:40 UTC, SebGrd commented on frontend/src/components/Input.jsx
> +  const customStyle = {
CSS Module du coup (discord)

2023-10-17 08:40 UTC, SebGrd commented on frontend/src/components/Input.jsx
> +export default function Input({
délègue les props en enlevant les props qui sont des attributs html. ça ressemblerait à ça :  { onChange, ...delegated }
Puis dans les attributs ton composant  :  {...delegated}

2023-10-17 16:14 UTC, mrpinkcat commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
On a décidé hier soir avec seb de garder cette règle

2023-10-17 16:15 UTC, mrpinkcat commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
Donc il faut remettre les `PropTypes`

2023-10-17 16:15 UTC, SebGrd commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
ça cause trop de problème donc on va éviter

2023-10-17 16:16 UTC, mrpinkcat commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
*on va éviter de l'enlever

2023-10-17 16:18 UTC, mrpinkcat commented on frontend/.eslintrc.cjs
> -    ],
C'est quoi ça ?

2023-10-17 16:19 UTC, Timdev0 commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
incompatible avec forwardRef() 
![image](https://github.com/ESGI-69/challenge-5A-S1/assets/32125474/bca4898a-a8ad-4fe0-911b-7a3ab4c66fc5)

2023-10-17 16:22 UTC, Timdev0 commented on frontend/.eslintrc.cjs
> -    ],
![image](https://github.com/ESGI-69/challenge-5A-S1/assets/32125474/b022e2bb-2142-4175-8a55-6b3607c083aa)

2023-10-17 16:23 UTC, mrpinkcat commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
Ça sert a quoi la forward ref ?

2023-10-17 16:23 UTC, mrpinkcat commented on frontend/.eslintrc.cjs
> -    ],
https://github.com/ESGI-69/challenge-5A-S1/pull/31#discussion_r1362415080

2023-10-17 16:24 UTC, Timdev0 commented on frontend/.eslintrc.cjs
> +    'react/prop-types': 'off',
alors au final cetait peut etre à cause de moi, je l'ai déplacer dans la function et je n'ai plus le warning
![image](https://github.com/ESGI-69/challenge-5A-S1/assets/32125474/33a3d968-df86-4bb2-b40b-07eaac657cad)

2023-10-18 00:24 UTC, mrpinkcat approved these changes

2023-10-18 00:26 UTC, SebGrd approved these changes

2023-10-18 00:27 UTC, merged