24 create the establishment entity
ESGI-69/challenge-5A-S1 pull request #36
Opened 2023-10-17 21:41 UTC by ycenta

2023-10-18 07:27 UTC, Timdev0 approved these changes

2023-10-18 12:12 UTC, mrpinkcat commented
Ça peut etre bien que tu détaille les nouveaux point d'api et ce que t'as fais en description de ta MR

2023-10-18 12:12 UTC, mrpinkcat requested changes
Ça peut etre bien que tu détaille les nouveaux point d'api et ce que t'as fais en description de ta MR

2023-10-20 08:55 UTC, ycenta commented
J'ai mis les endpoint:
Get
Post
Patch
Delete

Quand on Get, on recup l'objet Company aussi, j'ai mis quelques règles pour la création du genre : pas vide, entre 2-255 chars 
Et pour les position geographique:
-Long (entre -180 & 180)
-Lat (entre -90 & 90)

2023-10-20 08:58 UTC, mrpinkcat approved these changes

2023-10-21 14:07 UTC, sguenier approved these changes
Bien vu bien vu, rien à redire

2023-10-21 14:07 UTC, merged