22 add missing fileds user entity
ESGI-69/challenge-5A-S1 pull request #37
Opened 2023-10-18 08:57 UTC by Timdev0

2023-10-23 17:16 UTC, mrpinkcat approved these changes

2023-10-23 17:44 UTC, mrpinkcat commented on backend/migrations/Version20231018085520.php
> +        $this->addSql('ALTER TABLE "user" ADD company_id_id INT DEFAULT NULL');
company id id ???

2023-10-23 17:45 UTC, mrpinkcat requested changes
C'est louche ce company id id

2023-10-23 17:46 UTC, mrpinkcat submitted a review, later dismissed
My bad c'est un vielle migration

2023-10-24 17:28 UTC, mrpinkcat submitted a review, later dismissed

2023-10-25 10:12 UTC, SebGrd approved these changes

2023-10-25 19:06 UTC, sguenier approved these changes
Super Gut

2023-10-25 19:06 UTC, merged