feat(button_component): add button components
ESGI-69/challenge-5A-S1 pull request #40
Opened 2023-10-18 22:13 UTC by ycenta

2023-10-20 09:00 UTC, mrpinkcat commented on frontend/src/App.css
> +}
Pourquoi tu duplique le style du `button.module.scss` ici ?

2023-10-20 09:07 UTC, mrpinkcat commented on frontend/src/components/Button.jsx
> +  }
utilise plutôt un objet, les switch c'est de la merde

```suggestion
  const buttonClass = variantClasses[variant]
  
  const variantClasses = {
    primary: 'button--primary',
    success: 'button--success',
    danger: 'button--danger',
    warning: 'button--warning',
  }
```

2023-10-20 09:09 UTC, mrpinkcat commented on frontend/src/components/Button.jsx
> +  Object.assign(customStyle, style);
?

2023-10-20 09:10 UTC, mrpinkcat commented on frontend/src/assets/scss/button.module.scss
> +  }
pourquoi laisser une classe vide dans ce cas ?

2023-10-22 22:17 UTC, ycenta commented on frontend/src/App.css
> +}
parce que oubli

2023-10-22 23:22 UTC, SebGrd requested changes

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +      {title}
Le title ne sert pas à grand chose, tu peux le supprimer et laisser seulement children

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +  title = 'Title',
du coup le title ici aussi

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +  title = children ?? title;
et là

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +  onClick,
vu que tu délègues tes props après, le onClick ici est redondant et ne sert à rien

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +    <Component className={buttonClass} style={style} onClick={onClick} {...others}>
Pareil que onClick pour ce style

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +  style,
idem style

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +export default function Button({
On va en discuter plus tard mais applique un forward ref tel que:  
```javascript
export default React.forwardRef( ({ lesPropsQueTuVeux }, ref ) => {
  ...
  render(
    <Component ref={ref} ...
       ...
  )
})
```

2023-10-22 23:22 UTC, SebGrd commented on frontend/src/components/Button.jsx
> +export default function Button({
Ajoute un petit prop 'href' et si il est défini alors le component sera un <a> et pas un <button>

2023-10-24 06:41 UTC, SebGrd requested changes

2023-10-24 06:41 UTC, SebGrd commented on frontend/src/App.jsx
> +import Button from './components/lib/Button/Index';
Si tu rename ton fichier `index.js` (sans la maj) comme Gatien l'a fait sur sa mr des Tabs, tu vas pouvoir l'importer comme ça :  
```javascript
import Button from './components/lib/Button';
```

2023-10-24 06:41 UTC, SebGrd commented on frontend/src/components/lib/Button/Index.jsx
> +    <Element ref={ref} href={href} className={styles[variantClasses[variant]]} {...others}>
Il n'y a pas vraiment de convention en terme de nommage pour le rest des props mais on va essayer de tous mettre la même chose, soit `...delegated`  
Car ce sont les props délégués aux composants. Certains l'appellent aussi `...rest` mais ça veut aussi dire se reposer donc bon 🙂

2023-10-24 13:40 UTC, SebGrd approved these changes

2023-10-24 13:42 UTC, mrpinkcat approved these changes

2023-10-24 13:43 UTC, merged