44 Header Component
ESGI-69/challenge-5A-S1 pull request #60
Opened 2023-10-24 19:36 UTC by Timdev0

2023-10-26 12:04 UTC, mrpinkcat requested changes
Pour l'architecture de ton css prend exmeple sur https://github.com/ESGI-69/challenge-5A-S1/pull/67

2023-10-26 12:04 UTC, mrpinkcat commented on frontend/public/locales/en/main.json
> -  "doc": "Read the documentation!"
comme seb, les traduction doivent etre dans un fichier de page ou de composant, dans ton cas ils doivent etre dans le namespace topbar

2023-10-26 12:04 UTC, mrpinkcat commented on frontend/src/components/Header.module.scss
> +  padding: 1rem 2rem;
utilise les variables open props

2023-10-26 12:04 UTC, mrpinkcat commented on frontend/src/components/Header.module.scss
> +      font-weight: 700;
utilise les variables open props

2023-10-26 12:04 UTC, mrpinkcat commented on frontend/src/components/Header.module.scss
> +      font-size: 25px;
utilise les variables open props

2023-10-26 12:04 UTC, mrpinkcat commented on frontend/src/components/Header.module.scss
> +    gap: 1rem;
utilise les variables open props

2023-10-26 16:04 UTC, SebGrd requested changes

2023-10-26 16:04 UTC, SebGrd commented on frontend/src/components/Header.jsx
> +        <a href="/register" className={styles.navbar__menu__link}>{t('register')}</a>
Utilise un élément <Link> de "react-router-dom"

2023-10-26 16:33 UTC, mrpinkcat commented on frontend/src/components/Header.jsx
> +        <a href="/register" className={styles.navbar__menu__link}>{t('register')}</a>
<Link>

2023-10-26 17:23 UTC, mrpinkcat commented on frontend/src/components/Header.module.scss
> +  &__home {
```suggestion
.Navbar {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  padding: var(--size-3) var(--size-7);
  border-bottom: var(--border-size-1) solid var(--color-border);

  &Home {
```

Et du coup dans ton composant ça va etre ça pour utiliser la class `style.NavabarHome`

2023-10-26 21:18 UTC, SebGrd requested changes
<img width="1064" alt="image" src="https://github.com/ESGI-69/challenge-5A-S1/assets/43199628/0f938aaa-fe5e-4105-a63e-aeed1605d240">
Normal que ça soit comme ça ?

2023-10-27 23:58 UTC, mrpinkcat approved these changes

2023-10-30 17:35 UTC, SebGrd approved these changes

2023-10-30 17:35 UTC, merged