Backoffice Sidebar + Layout update
ESGI-69/challenge-5A-S1 pull request #62
Opened 2023-10-25 02:19 UTC by SebGrd

2023-10-25 04:41 UTC, SebGrd commented
<img width="1394" alt="image" src="https://github.com/ESGI-69/challenge-5A-S1/assets/43199628/b2f96832-ecf1-4802-9d2f-bf6bc47e586e">
<img width="1402" alt="image" src="https://github.com/ESGI-69/challenge-5A-S1/assets/43199628/9d8d2c86-e308-4a01-889a-932fd7a4f4b9">

2023-10-25 10:30 UTC, mrpinkcat requested changes
![image](https://github.com/ESGI-69/challenge-5A-S1/assets/13932200/5c5e3050-b525-4999-834c-abcb53c2cb83)

Chaud que tout les boutton soit à la meme width et de diviser le padding de la sidebar par deux

2023-10-25 18:29 UTC, mrpinkcat approved these changes

2023-10-25 18:32 UTC, mrpinkcat submitted a review, later dismissed

2023-10-25 21:26 UTC, mrpinkcat commented on frontend/src/pages/__layouts/backofficeLayout/BackofficeLayout.module.scss
> +    max-height: 100vh;
c'est mieux de ne pas utiliser les vh dans ce cas, il faut plutôt utiliser 100% qui se base sur la height de son parent

```
.html, .body {
  height: 100%;

  .layout {
    height: 100%;
  }
}
```

2023-10-25 21:30 UTC, mrpinkcat requested changes

2023-10-25 21:30 UTC, mrpinkcat commented on frontend/src/pages/__layouts/backofficeLayout/Sidemenu/index.jsx
> +              Statistiques
Traductions

2023-10-25 21:30 UTC, mrpinkcat commented on frontend/src/pages/__layouts/backofficeLayout/Sidemenu/index.jsx
> +              Employés
Traductions

2023-10-25 21:30 UTC, mrpinkcat commented on frontend/src/pages/__layouts/backofficeLayout/Sidemenu/index.jsx
> +              Etablissements
Traductions

2023-10-25 21:32 UTC, Timdev0 commented on frontend/src/pages/__layouts/backofficeLayout/BackofficeLayout.module.scss
> +    max-height: 100vh;
tout pareil

2023-10-26 10:57 UTC, mrpinkcat requested changes

2023-10-26 10:57 UTC, mrpinkcat commented on frontend/public/locales/en/backoffice.json
> +    "sidemenu": {
Il faut découper les traduction par composant ou page

2023-10-26 10:57 UTC, mrpinkcat commented on frontend/public/locales/en/backoffice.json
> +    "sidemenu": {
donc dans ce cans faut faire un name space sidemenu

2023-10-26 11:53 UTC, mrpinkcat approved these changes

2023-10-26 13:25 UTC, Timdev0 approved these changes

2023-10-26 13:25 UTC, merged