19 create tag component
ESGI-69/challenge-5A-S1 pull request #66
Opened 2023-10-25 20:22 UTC by sguenier

2023-10-25 21:31 UTC, mrpinkcat commented
Par pitié assignez vous a vos PR

2023-10-25 21:35 UTC, mrpinkcat approved these changes

2023-10-25 21:36 UTC, Timdev0 approved these changes

2023-10-26 15:41 UTC, SebGrd requested changes
La font size est trop grosse. Tu peux appliquer ça aux tags:
```css
font-size: var(--font-size-0);
```

2023-10-28 00:00 UTC, mrpinkcat requested changes

2023-10-28 00:00 UTC, mrpinkcat commented on frontend/src/components/lib/Tag/Tag.module.scss
> +        background-color: hsl(var(--green-6-hsl) / 30%);
Fais en une variable `--color-success-light`

2023-10-28 00:00 UTC, mrpinkcat commented on frontend/src/components/lib/Tag/Tag.module.scss
> +        background-color: hsl(var(--green-6-hsl) / 30%);
Etc pour les autrres

2023-11-01 16:37 UTC, mrpinkcat requested changes
Utilise la variable mère pour que si jamais on veuille changer la couleur d'un des variants on ai pas à tout changé

2023-11-01 16:37 UTC, mrpinkcat commented on frontend/src/variables.css
> +  --color-primary-light: hsl(var(--yellow-5-hsl) / 30%);
Du coup utilise la variable color primary

```suggestion
  --color-primary-light: hsl(var(--color-primary) / 30%);
```

2023-11-01 16:37 UTC, mrpinkcat commented on frontend/src/variables.css
> +  --color-danger-light: hsl(var(--red-7-hsl) / 30%);
```suggestion
  --color-danger-light: hsl(var(--color-danger) / 30%);
```

2023-11-01 16:37 UTC, mrpinkcat commented on frontend/src/variables.css
> +  --color-warning-light: hsl(var(--orange-5-hsl) / 30%);
```suggestion
  --color-warning-light: hsl(var(--color-warning) / 30%);
```

2023-11-01 16:37 UTC, mrpinkcat commented on frontend/src/variables.css
> +  --color-success-light: hsl(var(--green-6-hsl) / 30%);
```suggestion
  --color-success-light: hsl(var(--color-success) / 30%);
```

2023-11-02 16:01 UTC, mrpinkcat approved these changes
Nsm, pour les changes, c'est pas mal comme ça aussi

2023-11-02 16:04 UTC, SebGrd approved these changes

2023-11-02 16:05 UTC, merged