feat(gallery_component): add gallery component
ESGI-69/challenge-5A-S1 pull request #69
Opened 2023-10-25 22:53 UTC by ycenta

2023-10-25 22:54 UTC, mrpinkcat commented
Une petite vidéo/photo démo ?

2023-10-25 23:04 UTC, ycenta commented
> Une petite vidéo/photo démo ?
@mrpinkcat 
https://streamable.com/hbws2x
ça prend la taille du container dans lequel le cmponent se trouve, pour l'exemple j'ai ajouté un width:80% et un margin auto

2023-10-26 10:20 UTC, mrpinkcat requested changes
Pour blur tu peux utiliser https://developer.mozilla.org/fr/docs/Web/CSS/filter-function/blur

Pour le css fais la meme chose que https://github.com/ESGI-69/challenge-5A-S1/pull/67/files au niveau du nomage et de l'utilisation des classes

2023-10-26 19:34 UTC, mrpinkcat requested changes

2023-10-26 19:34 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +.rightPictures {
sépare pas les image de gauche et de droite, met tout dans la meme grid et utilise les grid areas

je t'ai fais un exemple ici https://grid.layoutit.com/?id=5NZrrPE

2023-10-26 21:30 UTC, ycenta commented
jsp pourquoi le rec lag mais trkl https://streamable.com/9ahrcf

2023-10-27 12:59 UTC, mrpinkcat requested changes

2023-10-27 12:59 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +    gap: 15px 15px;
utilise open props

2023-10-27 12:59 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +        border-radius: 15px;
utilise open props

2023-10-27 12:59 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +            "main main main second";
Du coup tu cache le more ? sur planity il ne le cache pas

![Capture d’écran 2023-10-27 à 14 56 30](https://github.com/ESGI-69/challenge-5A-S1/assets/13932200/072eaab7-2571-46eb-9b83-b0525ed4e5f9)

2023-10-27 12:59 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +            filter: blur(5px);
C'est more qui doit etre blur. C'est lui qui va servir de bouton pour afficher les photo en plein écran.

2023-10-27 13:00 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +            "main main main second";
Et il faut aussi que les contour du blur soit "tranchant" pas blur et qu'il y ai `voir les x photo` dessus

2023-10-30 14:25 UTC, mrpinkcat requested changes
Pense aussi à afficher la 5eme image au lieu du bouton si il n'y a pas plus de 5 images 👍

2023-10-30 14:25 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +    gap: var(--size-4) var(--size-4);
Tu peux en mettre qu'un si les deux sont les meme 😉

2023-10-30 14:25 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/index.jsx
> +            {index === 4 ? <Button href="javascript:void" className={styles.GalleryMoreBtn}>voir les {pictures.length} photos</Button> : null}
Manque la traduction ici.

Tu peux créer un nouveau namespace gallery.json et utiliser la plurialisation (https://www.i18next.com/translation-function/plurals#singular-plural) et l'interpolation (https://www.i18next.com/translation-function/interpolation)

2023-11-02 13:49 UTC, mrpinkcat requested changes
Mis a part les petites traduction, c'est top 👍

2023-11-02 13:49 UTC, mrpinkcat commented on frontend/public/locales/en/gallery.json
> +    "viewPhotos_other": "View {{count}} Photos"
```suggestion
    "viewPhotos": "View more photos",
    "viewPhotos_other": "View all {{count}} photos"
```

2023-11-02 14:02 UTC, mrpinkcat requested changes
une dernière remarque sur les grids

2023-11-02 14:02 UTC, mrpinkcat commented on frontend/src/components/lib/Gallery/gallery.module.scss
> +    grid-template-rows: var(--size-13);
```suggestion
    grid-template-rows: var(--size-13) var(--size-13);
```

Il faut que tu définisse la taille des deux lignes ici. Sinon une seule ligne va faire cette taille

---

```suggestion
    grid-auto-rows: var(--size-13);
```

Sinon tu peux utiliser `grid-auto-rows` qui définie la taille de toutes les ligne de la grid

--- 

```suggestion
    grid-template-rows: 1fr 1fr;
```

Mais dans le cas actuel, il vaut mieux que tu définisse chaque ligne comme étant de taille `1fr`. Comme ça chaque ligne prendra la moitié de la hauteur du composant.

Grace a ça, le composant aura toujours un ratio de `1fr 1fr 1fr 1fr` sur `1fr 1fr` (soit 2/1)

2023-11-04 22:52 UTC, mrpinkcat approved these changes

2023-11-06 07:09 UTC, SebGrd approved these changes

2023-11-06 07:09 UTC, merged