85 services table component
ESGI-69/challenge-5A-S1 pull request #90
Opened 2023-10-30 20:15 UTC by Timdev0

2023-11-02 17:37 UTC, mrpinkcat requested changes

2023-11-02 17:37 UTC, mrpinkcat commented on frontend/src/components/Services/ServicesRow/index.jsx
> +      <Button className={style.ServicesRowBtn} variant="dark">Choisir</Button>
Une trad ici ?

Et si tu veux mettre du style dessus, wrap le dans un composant. La tu écrase le style du composant

```suggestion
     <div className={style.ServicesRowBtn}>
        <Button variant="dark">Choisir</Button>
      </div>
```

```scss
justify-self: flex-end;
```

2023-11-03 16:21 UTC, SebGrd approved these changes

2023-11-03 17:11 UTC, mrpinkcat approved these changes

2023-11-03 17:11 UTC, merged